#!/usr/bin/env bash

set -euo pipefail

echo "Caching apt..."
tar -cf 'cache-apt.tar' -C '/' 'var/cache/apt'

if [ -d '/var/tmp/curl' ]; then
	echo "Caching curl..."
	tar -cf 'cache-curl.tar' -C '/' 'var/tmp/curl'
else
	echo "Skipped caching curl..."
fi

if [ -d '/var/tmp/micromamba' ]; then
	echo "Caching micromamba..."
	tar -cf 'cache-micromamba.tar' -C '/' 'var/tmp/micromamba'
else
	echo "Skipped caching micromamba..."
fi

if [ -d '/var/tmp/elan' ]; then
	echo "Caching elan..."
	tar -cf 'cache-elan.tar' -C '/' 'var/tmp/elan'
else
	echo "Skipped caching elan..."
fi

if [ -d '/var/tmp/nvm' ]; then
	echo "Caching nvm..."
	tar -cf 'cache-nvm.tar' -C '/' 'var/tmp/nvm'
else
	echo "Skipped caching nvm..."
fi

if [ -d '/var/tmp/npm' ]; then
	echo "Caching npm..."
	tar -cf 'cache-npm.tar' -C '/' 'var/tmp/npm'
else
	echo "Skipped caching npm..."
fi
