#!/usr/bin/env bash

set -euo pipefail

cache() {
	if [ -d "${2}/${3}" ]; then
		echo "Caching ${1}..."
		tar -cf "cache-${1}.tar" -C "${2}" "${3}"
	else
		echo "Skipped caching ${1}..."
	fi
}

cache 'lean' "${HOME}" '.elan/toolchains'
cache 'micromamba' "${HOME}" 'micromamba/pkgs'
cache 'npm' "${HOME}" '.npm/_cacache'
cache 'nvm' "${HOME}" '.nvm/.cache'
