#!/usr/bin/env bash

set -euo pipefail

cache() {
	if [ -d "${2}/${3}" ]; then
		echo "Caching ${1}..."
		tar -cf "cache-${1}.tar" -C "${2}" "${3}"
	else
		echo "Skipped caching ${1}..."
	fi
}

cache 'apt' '/' 'var/cache/apt'
cache 'curl' '/' 'var/tmp/curl'
