#!/usr/bin/env bash

set -euo pipefail

echo 'Installing gnupg...'
apt-get -y install gnupg > /dev/null
echo 'Installing patch...'
apt-get -y install patch > /dev/null
echo

sed -i '/PS1.*\\\$/s/\\\$/\\n\0/' '/etc/skel/.bashrc'
'/usr/lib/wsl/oobe.sh'

username=$(ls /home)

cat <<-EOF > '/etc/wsl.conf'
	[boot]
	systemd = true

	[automount]
	options = "metadata"

	[user]
	default = ${username}
EOF

cat <<-'EOF' > '/etc/profile.d/gnupg.sh'
	gpg_tty() { tty > /dev/null && export GPG_TTY=$(tty); }
	gpg() { gpg_tty; command gpg "$@"; }

	gpg_tty
EOF
