#!/usr/bin/env bash

set -euo pipefail

username=$(ls /home)

if [ -f 'cache-micromamba.tar' ]; then
	echo 'Found: cache-micromamba.tar'
	tar -xf 'cache-micromamba.tar' -C '/'
	chmod 777 '/var/tmp/micromamba'
else
	echo 'Not found: cache-micromamba.tar'
	mkdir '/var/tmp/micromamba'
	chmod 777 '/var/tmp/micromamba'
fi

su "${username}" <<-'EOF'
	mkdir -p "${HOME}/micromamba"
	ln -s '/var/tmp/micromamba' "${HOME}/micromamba/pkgs"
EOF

if [ -f 'cache-elan.tar' ]; then
	echo 'Found: cache-elan.tar'
	tar -xf 'cache-elan.tar' -C '/'
	chmod 777 '/var/tmp/elan'
else
	echo 'Not found: cache-elan.tar'
	mkdir '/var/tmp/elan'
	chmod 777 '/var/tmp/elan'
fi

su "${username}" <<-'EOF'
	mkdir -p "${HOME}/.elan"
	ln -s '/var/tmp/elan' "${HOME}/.elan/toolchains"
EOF

if [ -f 'cache-nvm.tar' ]; then
	echo 'Found: cache-nvm.tar'
	tar -xf 'cache-nvm.tar' -C '/'
	chmod 777 '/var/tmp/nvm'
else
	echo 'Not found: cache-nvm.tar'
	mkdir '/var/tmp/nvm'
	chmod 777 '/var/tmp/nvm'
fi

su "${username}" <<-'EOF'
	mkdir -p "${HOME}/.nvm"
	ln -s '/var/tmp/nvm' "${HOME}/.nvm/.cache"
EOF
