#!/usr/bin/env bash

set -euo pipefail

echo "Installing micromamba..."
'cache-curl' 'https://micro.mamba.pm/api/micromamba/linux-64/latest' | tar -jxC "${HOME}" 'bin/micromamba'
bash -l <<-'EOF'
	set -euo pipefail
	micromamba shell init -s bash -r "${HOME}/micromamba" > /dev/null
	micromamba config append channels 'conda-forge' > /dev/null
	micromamba config set channel_priority 'strict' > /dev/null
EOF
echo

echo "Installing elan..."
'cache-curl' 'https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh' | sh -s -- -y
echo

echo "Installing nvm..."
(export NODE_VERSION='node' && 'cache-curl' 'https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh' | bash > /dev/null)
echo

echo "Installing python..."
bash -l <<-'EOF'
	micromamba env create -y -n 'python' python > /dev/null
EOF
echo

echo "Installing lean..."
bash -l <<-'EOF'
	lean_install() { (set -x; elan toolchain install "${1}" > /dev/null; { set +x; } 2> /dev/null) || printf ''; }

	lean_install `curl -s 'https://api.github.com/repos/leanprover/lean4/tags' | sed '/name/!d;/rc/d;s/.*\(v[^"]*\).*/\1/;q'`
EOF
