#!/usr/bin/env bash

set -euo pipefail

uncache() {
	if [ -f "cache-${1}.tar" ]; then
		echo "Found: cache-${1}.tar"
		tar -xf "cache-${1}.tar" -C "${2}"
	else
		echo "Not found: cache-${1}.tar"
	fi
}

uncache 'lean' "${HOME}"
uncache 'micromamba' "${HOME}"
uncache 'npm' "${HOME}"
uncache 'nvm' "${HOME}"
