#!/usr/bin/env bash

set -euo pipefail

apt_get() { set -x && apt-get "${@}" > /dev/null && { set +x; } 2> /dev/null; }

apt_get -y install bzip2
apt_get -y install curl
echo

echo "Installing neovim..."
'cache-curl' 'https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz' | tar -xzC '/opt'
echo

cat <<-'EOF' > '/etc/profile.d/nvim.sh'
	export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
EOF

echo "Installing golang..."
'cache-curl' "https://go.dev/dl/$(curl -s 'https://go.dev/VERSION?m=text' | head -n1).linux-amd64.tar.gz" | tar -xzC '/usr/local'
echo

cat <<-'EOF' > '/etc/profile.d/golang.sh'
	export PATH="$PATH:/usr/local/go/bin"
EOF

apt_get -y install latexmk
apt_get -y install texlive-bibtex-extra
apt_get -y install texlive-xetex

(
	cd /home
	mkdir node_modules
	echo '{}' > package.json
	echo '{}' > package-lock.json
	chmod 777 node_modules package.json package-lock.json
)
