#!/usr/bin/env bash

set -euo pipefail

if [ -f 'cache-apt.tar' ]; then
	echo 'Found: cache-apt.tar'
	tar -xf 'cache-apt.tar' -C '/'
else
	echo 'Not found: cache-apt.tar'
fi

if [ -f 'cache-curl.tar' ]; then
	echo 'Found: cache-curl.tar'
	tar -xf 'cache-curl.tar' -C '/'
	chmod 777 '/var/tmp/curl'
else
	echo 'Not found: cache-curl.tar'
	mkdir '/var/tmp/curl'
	chmod 777 '/var/tmp/curl'
fi

cp 'cache-curl' '/usr/local/bin'
